const TELEGRAM_MESSAGE_MAX_LENGTH = 3500;
const DEFAULT_BROADCAST_PAUSE_MS = 300;
const MAX_RETRY_COUNT = 2;

export {
  TELEGRAM_MESSAGE_MAX_LENGTH,
  DEFAULT_BROADCAST_PAUSE_MS,
  MAX_RETRY_COUNT,
};
