const TELEGRAM_MESSAGE_MAX_LENGTH = 3500;
const DEFAULT_BROADCAST_PAUSE_MS = 300;
const DEFAULT_MAX_PINNED_COUNT = 10;

export {
  TELEGRAM_MESSAGE_MAX_LENGTH,
  DEFAULT_BROADCAST_PAUSE_MS,
  DEFAULT_MAX_PINNED_COUNT,
};
